name: Build JIT

on:
  workflow_dispatch:
  push:
    paths:
      - 'libs/liblua_shared_lib_*'
      - 'libs/lua_shared_lib_*'
      - 'LuaJIT-2.1/**'

jobs:
  build-windows-64:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - uses: ilammy/msvc-dev-cmd@v1
      - name: Generate libs
        run: |
          cd LuaJIT-2.1/src/
          .\msvcbuild.bat
          ren lua51.lib lua51_64.lib
          ren luajit.lib luajit_64.lib

      - uses: actions/upload-artifact@v4
        name: Upload lua51.lib
        with:
          name: lua51_64.lib
          path: LuaJIT-2.1/src/lua51_64.lib
          retention-days: 1

      - uses: actions/upload-artifact@v4
        name: Upload luajit.lib
        with:
          name: luajit_64.lib
          path: LuaJIT-2.1/src/luajit_64.lib
          retention-days: 1

  build-windows-32:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - uses: ilammy/msvc-dev-cmd@v1
      - name: Generate libs
        run: |
          cd LuaJIT-2.1/src/
          .\msvcbuild_86.bat
          ren lua51.lib lua51_32.lib
          ren luajit.lib luajit_32.lib

      - uses: actions/upload-artifact@v4
        name: Upload lua51.lib
        with:
          name: lua51_32.lib
          path: LuaJIT-2.1/src/lua51_32.lib
          retention-days: 1

      - uses: actions/upload-artifact@v4
        name: Upload luajit.lib
        with:
          name: luajit_32.lib
          path: LuaJIT-2.1/src/luajit_32.lib
          retention-days: 1

  build-linux-64:
    runs-on: ubuntu-latest
    container: debian:bullseye
    steps:
      - name: Install Dependencies
        run: |
          apt update
          apt install -y build-essential

      - uses: actions/checkout@v4
        name: Checkout

      - uses: ilammy/msvc-dev-cmd@v1
      - name: Generate libs
        run: |
          cd LuaJIT-2.1/src/
          make CC='$(DEFAULT_CC) -fPIC' LIBS='-llua_shared_lib_64'
          mv libluajit.a libluajit_64.a

      - uses: actions/upload-artifact@v4
        name: Upload libluajit.a (64x)
        with:
          name: libluajit_64.a
          path: LuaJIT-2.1/src/libluajit_64.a
          retention-days: 1

  build-linux-32:
    runs-on: ubuntu-latest
    container: debian:bullseye
    steps:
      - name: Install Dependencies
        run: |
          dpkg --add-architecture i386
          apt update
          apt install -y build-essential gcc-multilib g++-multilib

      - uses: actions/checkout@v4
        name: Checkout

      - uses: ilammy/msvc-dev-cmd@v1
      - name: Generate libs
        run: |
          cd LuaJIT-2.1/src/
          make CC='$(DEFAULT_CC) -m32' LIBS='-llua_shared_lib_32'
          mv libluajit.a libluajit_32.a

      - uses: actions/upload-artifact@v4
        name: Upload libluajit.a (32x)
        with:
          name: libluajit_32.a
          path: LuaJIT-2.1/src/libluajit_32.a
          retention-days: 1