name: Build lua_shared_lib

on:
  workflow_dispatch:
  push:
    paths:
      - 'lua_shared_lib/**'

jobs:
  build:
    uses: RaphaelIT7/gmod-common-module-base/.github/workflows/compile.yml@workflow
    with:
      PROJECT_NAME: "lua_shared_lib"
      BUILD_64x: "true"
      LINUX_FILEEXTENTION: "a"
      WINDOWS_FILEEXTENTION: "lib"
      BUILD_WINDOWS: "true"
      ARTIFACT_EXPIRE: "1"
      USE_PREFIX: "false"
      PROJECT_PATH: "lua_shared_lib/"