name: Build Project

on:
  push:
    paths:
      - 'libs/**'
      - 'source/**'
      - 'premake5.lua'

jobs:
  build:
    uses: RaphaelIT7/gmod-common-module-base/.github/workflows/compile.yml@workflow
    with:
      PROJECT_NAME: "lua_shared"
      BUILD_64x: "true"
      LINUX_FILEEXTENTION: "so"
      BUILD_WINDOWS: "true"
      ARTIFACT_EXPIRE: "1"
      SOURCESDK_MINIMAL: "RaphaelIT7/sourcesdk-minimal"
      SOURCESDK_MINIMAL_BRANCH: "patch-2"
      SOURCESDK_MINIMAL_64XBRANCH: "temp-64x"