name: Build Project

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'libs/lua51*'
      - 'libs/luajit*'
      - 'libs/libluajit*'
      - 'libs/bootil_static*'
      - 'libs/libbootil_static*'
      - 'source/**'
      - 'premake5.lua'

jobs:
  build:
    uses: RaphaelIT7/gmod-common-module-base/.github/workflows/compile.yml@workflow
    with:
      PROJECT_NAME: "lua_shared"
      BUILD_64x: "true"
      LINUX_FILEEXTENTION: "so"
      BUILD_WINDOWS: "true"
      ARTIFACT_EXPIRE: "1"
      USE_PREFIX: "false"