name: Build Testing

on:
  workflow_dispatch:
  workflow_call:

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
        with:
          sparse-checkout: "_testing/"

      - name: Delete lua_shared_srv.so
        run: |
          curl "https://${{secrets.PTERODACTYL_URL}}/api/client/servers/${{secrets.PTERODACTYL_SERVER}}/files/delete" \
            -H 'Accept: application/json' \
            -H 'Authorization: Bearer ${{secrets.PTERODACTYL_KEY}}' \
            -X POST \
            --data '{ "root": "/garrysmod/bin/", "files": [ "lua_shared_srv.so" ] }'

      - name: Rename lua_shared.so to lua_shared_srv.so
        run: |
          curl "https://${{secrets.PTERODACTYL_URL}}/api/client/servers/${{secrets.PTERODACTYL_SERVER}}/files/rename" \
            -H 'Accept: application/json' \
            -H 'Authorization: Bearer ${{secrets.PTERODACTYL_KEY}}' \
            -X POST \
            --data '{ "root": "/garrysmod/bin/", "files": [ { "from": "lua_shared.so", "to": "lua_shared_srv.so" } ] }'

      - uses: ilammy/msvc-dev-cmd@v1
      - uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.1.5"

      - name: Testing
        run: |
          cd _testing
          lua console.lua ${{secrets.PTERODACTYL_URL}} ${{secrets.PTERODACTYL_SERVER}} ${{secrets.PTERODACTYL_KEY}}